### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'configs/agents/local/turbo.yaml'

### ISSUE THREAD

**Issue by foamliu** [THUDM/AgentBench#10]
I got this error while executing the lateral thinking puzzle task, I looked in the config file, there is a link to this file but it is not in the repo.

**Comment by Longin-Yu** [comment]
Thanks. We have fix this error already. Now using "configs/agents/api_agents/gpt-3.5-turbo.yaml"

**Comment by foamliu** [comment]
Thanks Reply. In fact, I noticed that the agent has already been initialized in the eval.py file, why should it be initialized again in the LTP task? Which agent is used in the evaluation? I ask this because I created a custom llama agent, and the LTP task settings make the system load the same llama model twice, resulting in out of memory error.

**Comment by zhc7** [comment]
ltp do use a small model for task setting. Please refer to our paper.

**Comment by Longin-Yu** [comment]
Feel free to reopen this issue if any problem still exists.
