### ISSUE TITLE
[Bug/Assistance] "result": {"answer": "1049 (42000): Unknown database 'Football Matches'", "type": "UPDATE", "error"

### ISSUE THREAD

**Issue by 13416157913** [THUDM/AgentBench#111]
agent、server、assigner都正常启动了，run.jsonl文件能够获得模型回答；但是日志全部都是报错没有以下这个错误：
{"index": 295, "error": null, "info": null, "output": {"index": 295, "status": "agent validation failed", "result": {"answer": "1049 (42000): Unknown database 'Football Matches'", "type": "UPDATE", "error": ""}, "history": [{"role": "user", "content": "\nI will ask you a question, then you should help me operate a MySQL database with SQL to answer the question.\nYou have to explain the problem and your solution to me and write down your thoughts.\nAfter thinking and explaining thoroughly, every round you can choose to operate or to answer.\nyour operation should be like this:\nAction: Operation\n```sql\nSELECT * FROM table WHERE condition;\n```\nYou MUST put SQL in markdown format without any other comments. Your SQL should be in one line.\nEvery time you can only execute one SQL statement. I will only execute the statement in the first SQL code block. Every time you write a SQL, I will execute it for you and give you the output.\nIf you are done operating, and you want to commit your final answer, then write down:\nAction: Answer\nFinal Answer: [\"ANSWER1\", \"ANSWER2\", ...]\nDO NOT write this pattern unless you are sure about your answer. I expect an accurate and correct answer.\nYour answer should be accurate. Your answer must be exactly the same as the correct answer.\nIf the question is about modifying the database, then after done operation, your answer field can be anything.\nIf your response cannot match any pattern I mentioned earlier, you will be judged as FAIL immediately.\nYour input will be raw MySQL response, you have to deal with it by yourself.\n"}, {"role": "agent", "content": "Ok."}, {"role": "user", "content": "Set the score of tie number 1 in the Football Matches table to '2 - 2'.\nThe name of this table is Football Matches, and the headers of this table are Tie no,Home team,Score,Away team,Date,Attendance."}, {"role": "agent", "content": "Action: Operation\n```sql\nUPDATE Football_Matches SET Score = '2 - 2' WHERE Tie_no = 1;\n```\n解释：这个SQL语句会更新名为\"Football_Matches\"的表中的\"Score\"列，将\"Tie_no\"为1的行的值更改为'2 - 2'。这样，我们就成功地将第一场足球比赛的比分设置为了'2 - 2'。 "}, {"role": "user", "content": "1049 (42000): Unknown database 'Football Matches'"}, {"role": "agent", "content": "根据您提供的信息，我无法找到数据库“Football Matches”。请确保您已经创建了这个数据库，并且可以正常连接到它。如果您还没有创建这个数据库，您需要先创建它，然后才能进行后续的操作。\n\n如果您已经创建了这个数据库，但仍然遇到这个问题，可能是由于连接参数不正确或者权限不足等原因导致的。请确保您的连接参数正确，并且您有权限对这个数据库进行操作。\n\n如果您需要进一步的帮助，请提供更多关于您的数据库环境和问题的详细信息，以便我能够更好地帮助您。 "}]}, "time": {"timestamp": 1706786285798, "str": "2024-02-01 19:18:05"}}
{"index": 296, "error": null, "info": null, "output": {"index": 296, "status": "agent validation failed", "result": {"answer": "1049 (42000): Unknown database 'Olympic Medal Table'", "type": "UPDATE", "error": ""}, "history": [{"role": "user", "content": "\nI will ask you a question, then you should help me operate a MySQL database with SQL to answer the question.\nYou have to explain the problem and your solution to me and write down your thoughts.\nAfter thinking and explaining thoroughly, every round you can choose to operate or to answer.\nyour operation should be like this:\nAction: Operation\n```sql\nSELECT * FROM table WHERE condition;\n```\nYou MUST put SQL in markdown format without any other comments. Your SQL should be in one line.\nEvery time you can only execute one SQL statement. I will only execute the statement in the first SQL code block. Every time you write a SQL, I will execute it for you and give you the output.\nIf you are done operating, and you want to commit your final answer, then write down:\nAction: Answer\nFinal Answer: [\"ANSWER1\", \"ANSWER2\", ...]\nDO NOT write this pattern unless you are sure about your answer. I expect an accurate and correct answer.\nYour answer should be accurate. Your answer must be exactly the same as the correct answer.\nIf the question is about modifying the database, then after done operation, your answer field can be anything.\nIf your response cannot match any pattern I mentioned earlier, you will be judged as FAIL immediately.\nYour input will be raw MySQL response, you have to deal with it by yourself.\n"}, {"role": "agent", "content": "Ok."}, {"role": "user", "content": "The Olympic Medal Table was updated to set the gold medal count to 2 and total medal count to 3 for the rank of 6.\nThe name of this table is Olympic Medal Table, and the headers of this table are Rank,Gold,Silver,Bronze,Total."}, {"role": "agent", "content": "根据您提供的信息，我们可以使用SQL来更新Olympic Medal Table中的数据。以下是操作步骤：\n\n1. 连接到MySQL数据库。\n2. 找到Olympic Medal Table所在的数据库和表。\n3. 编写SQL语句来更新数据。\n\n具体来说，我们可以使用以下SQL语句来更新Olympic Medal Table中的数据：\n\n\n```sql\nUPDATE Olympic_Medal_Table\nSET Gold = 2, Total = 3\nWHERE Rank = 6;\n```\n这条SQL语句的意思是：在Olympic_Medal_Table表中，将Rank为6的行的Gold列设置为2，Total列设置为3。\n\n执行完这条SQL语句后，Olympic Medal Table中的数据将被更新为：\n\n\n| Rank | Gold | Silver | Bronze | Total |\n| :--: | :--: | :--: | :--: | :--: |\n| 1 | 10 | 5 | 3 | 18 |\n| 2 | 8 | 4 | 2 | 14 |\n| 3 | 6 | 3 | 1 | 10 |\n| 4 | 4 | 2 | 0 | 6 |\n| 5 | 2 | 1 | 0 | 3 |\n| **6** | **2** | **0** | **0** | **3** |\n| ... | ... | ... | ... | ... |\n\n请注意，执行SQL语句时需要确保数据库连接已经建立，并且有权限对Olympic Medal Table进行修改。此外，执行完SQL语句后，应该检查数据是否已经被正确地更新。如果需要进一步的帮助，请提供更多的信息。 "}]}, "time": {"timestamp": 1706786289425, "str": "2024-02-01 19:18:09"}}

是不是mysql容器中数据库要初始化，先创建数据库和表等等....，目前检查mysql容器，登录mysql数据库里面都是默认状态，除了系统库和表，没有其他数据库；
![image](https://github.com/THUDM/AgentBench/assets/20581199/cc00af28-1b2d-4b37-91af-75989cde822c)

**Comment by zhc7** [comment]
Hi, @13416157913 框架会自动创建mysql容器并初始化，评测结束后容器里的mysql数据表会自动删除，完全结束以后容器也会被删除，可以尝试在运行还没有结束的时候查看一下。
