### ISSUE TITLE
[Bug/Assistance] OS任务报错AttributeError: 'NpipeSocket' object has no attribute '_sock'

### ISSUE THREAD

**Issue by 13416157913** [THUDM/AgentBench#112]
AgentBench\src\server\tasks\os_interaction\task.py", line 37, in __init__
AttributeError: 'NpipeSocket' object has no attribute '_sock'\n"

**Comment by zhc7** [comment]
Hi, @13416157913 你是在Windows上跑的吗？可以尝试在Linux或者WSL内跑一下试试

**Comment by 13416157913** [comment]
> Hi, @13416157913 你是在Windows上跑的吗？可以尝试在Linux或者WSL内跑一下试试

确实是windows的问题，在WSL内跑可以了；
