### ISSUE TITLE
[Bug/Assistance] 测试os-std任务，提示Message: 0 samples remaining.

### ISSUE THREAD

**Issue by 13416157913** [THUDM/AgentBench#113]
启动方式：
1、python -m src.start_task -a
2、python -m src.assigner
![image](https://github.com/THUDM/AgentBench/assets/20581199/a3480dd7-9d16-4faf-86e1-e80947faaed0)
![image](https://github.com/THUDM/AgentBench/assets/20581199/9b8f3561-7b21-41f2-a544-f5f36dc4837e)

**Comment by zhc7** [comment]
Hi, @13416157913 有可能是因为指定的输出文件夹里已经包含了全部的测试结果，框架不会重复测试。如果想要重新跑的话，可以尝试换一个输出路径。

**Comment by 13416157913** [comment]
> 因为指定的输出文件夹里已经包含了

os-std输出文件目录已经删除了，再运行的代码的；

**Comment by zhc7** [comment]
可以看一下你的配置文件吗？

**Comment by 13416157913** [comment]
> 下你的配置

assignments:
- agent: pci-chatgpt
  task: os-std
concurrency:
  agent:
    pci-chatgpt: 5
  task:
    os-std: 5
definition:
  agent:
    pci-chatgpt:
      module: src.client.agents.FastChatAgent
      parameters:
        body:
          max_tokens: 4096
          model: pci-chatgpt
          repetition_penalty: 1.2
          temperature: 0.05
          top_k: 30
          top_p: 0.8
        controller_address: http://123.249.36.167:19201
        headers:
          Content-Type: application/json
        max_new_tokens: 4096
        model_name: pci-chatgpt
        name: FastChat
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        repetition_penalty: 1.2
        return_format: '{response[choices][0][message][content]}'
        temperature: 0.05
        top_k: 30
        top_p: 0.8
        url: http://123.249.36.167:19201/api/gpt/chat/completions
  task:
    os-std:
      module: src.client.TaskClient
      parameters:
        concurrency: 24
        controller_address: http://localhost:5000/api
        data_config:
          bk: []
          files:
          - index_prefix: std-001-
            problem_file: ../data/os_interaction/data/1/*.json
            script_dir: ../data/os_interaction/scripts/1/
          - index_prefix: std-002-
            problem_file: ../data/os_interaction/data/2/*.json
            script_dir: ../data/os_interaction/scripts/2/
          - index_prefix: std-003-
            problem_file: ../data/os_interaction/data/3/*.json
            script_dir: ../data/os_interaction/scripts/3/
          - index_prefix: std-004-
            problem_file: ../data/os_interaction/data/4/*.json
            script_dir: ../data/os_interaction/scripts/4/
          - index_prefix: std-005-
            problem_file: ../data/os_interaction/data/5/*.json
            script_dir: ../data/os_interaction/scripts/5/
          - index_prefix: std-006-
            problem_file: ../data/os_interaction/data/6/*.json
            script_dir: ../data/os_interaction/scripts/6/
          - index_prefix: std-007-
            problem_file: ../data/os_interaction/data/7/*.json
            script_dir: ../data/os_interaction/scripts/7/
          ignore: []
        docker_config:
          directory: ../data/os_interaction/res/dockerfiles
          localhost: local-os
        name: os-std
        round_limit: 8
        scripts:
          directory: ../data/os_interaction/scripts
output: outputs/2024-02-02-18-27-06

**Comment by 13416157913** [comment]
> 可以看一下你的配置文件吗？

assignments:
- agent: pci-chatgpt
  task: os-std
concurrency:
  agent:
    pci-chatgpt: 5
  task:
    os-std: 5
definition:
  agent:
    pci-chatgpt:
      module: src.client.agents.FastChatAgent
      parameters:
        body:
          max_tokens: 4096
          model: pci-chatgpt
          repetition_penalty: 1.2
          temperature: 0.05
          top_k: 30
          top_p: 0.8
        controller_address: http://xxx.xxx.xxx.xxx:10001
        headers:
          Content-Type: application/json
        max_new_tokens: 4096
        model_name: pci-chatgpt
        name: FastChat
        prompter:
          args:
            agent_role: assistant
          name: role_content_dict
        repetition_penalty: 1.2
        return_format: '{response[choices][0][message][content]}'
        temperature: 0.05
        top_k: 30
        top_p: 0.8
        url: http://xxx.xxx.xxx.xxx:10001/api/gpt/chat/completions
  task:
    os-std:
      module: src.client.TaskClient
      parameters:
        concurrency: 24
        controller_address: http://localhost:5000/api
        data_config:
          bk: []
          files:
          - index_prefix: std-001-
            problem_file: ../data/os_interaction/data/1/*.json
            script_dir: ../data/os_interaction/scripts/1/
          - index_prefix: std-002-
            problem_file: ../data/os_interaction/data/2/*.json
            script_dir: ../data/os_interaction/scripts/2/
          - index_prefix: std-003-
            problem_file: ../data/os_interaction/data/3/*.json
            script_dir: ../data/os_interaction/scripts/3/
          - index_prefix: std-004-
            problem_file: ../data/os_interaction/data/4/*.json
            script_dir: ../data/os_interaction/scripts/4/
          - index_prefix: std-005-
            problem_file: ../data/os_interaction/data/5/*.json
            script_dir: ../data/os_interaction/scripts/5/
          - index_prefix: std-006-
            problem_file: ../data/os_interaction/data/6/*.json
            script_dir: ../data/os_interaction/scripts/6/
          - index_prefix: std-007-
            problem_file: ../data/os_interaction/data/7/*.json
            script_dir: ../data/os_interaction/scripts/7/
          ignore: []
        docker_config:
          directory: ../data/os_interaction/res/dockerfiles
          localhost: local-os
        name: os-std
        round_limit: 8
        scripts:
          directory: ../data/os_interaction/scripts
output: outputs/2024-02-02-18-27-06

**Comment by 13416157913** [comment]
> 可以看一下你的配置文件吗？

您好，请问是什么原因，os任务提示Message: 0 samples remaining. db任务能正常运行。

**Comment by 13416157913** [comment]
> 可以看一下你的配置文件吗？

问题已解决，是配置问题。

**Comment by yuerunyu** [comment]
> > 可以看一下你的配置文件吗？
> 
> 问题已解决，是配置问题。

请问下dbbench-std任务怎么跑起来的，能给点详细的指导吗？我现在是os-std可以，dbbench-std任务不行。
