### ISSUE TITLE
[Bug/Assistance] kg-std任务运行的runs.jsonl文件中问题在数据集中找不到

### ISSUE THREAD

**Issue by 13416157913** [THUDM/AgentBench#116]
以下这个日志是在运行kg-std任务时，从run日志中查看记录，其中Question对应的问题，怎么在data/knowledgegraph/std.json文件中没有找到相应的问题？
{"role": "user", "content": "Question: the bipropellant rocket engine with kerosene and gas-generator cycle is designed by who? \n
Entities: [Gas-generator cycle, Kerosene]"},

**Comment by zhc7** [comment]
Hi, @13416157913 run.jsonl的条目里应该是有记录index的

**Comment by 13416157913** [comment]
> Hi, @13416157913 run.jsonl的条目里应该是有记录index的

但是kg的数据集std.json中没有index。

**Comment by zhc7** [comment]
index是几就代表第几行，从0开始计算。详见https://github.com/THUDM/AgentBench/blob/213093cf723901e43a2ec06627ce247e1bf6137f/src/server/tasks/knowledgegraph/task.py#L158

**Comment by zhc7** [comment]
If you have any further questions, feel free to reopen the issue!
