### ISSUE TITLE
[Feature] Use for benchmarking agents like AutoGPT?

### ISSUE THREAD

**Issue by shruti222patel** [THUDM/AgentBench#118]
Hi,

Can this repo be used for testing and benchmarking general agent frameworks like AutoGPT? Are there docs around this or could you point me to the code files I would need to update to make this work?

Thanks!

**Comment by zhc7** [comment]
Hi, @shruti222patel . Yes, it is possible. Writing a new client for each agent framework should be sufficient. You may refer to https://github.com/THUDM/AgentBench/blob/main/docs/Introduction_en.md#23-client. If this does not meet your requirement, you might have to change the core interaction logic in `src/assigner.py`.
