### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/mind2web/prompt/llm_prompt_cot.json'

### ISSUE THREAD

**Issue by ustc-mkh** [THUDM/AgentBench#12]
It seems that the file was not uploaded. I can't find it in the docker image either.

**Comment by scottsuk0306** [comment]
@ustc-mkh I'm experiencing similar issue. In fact, I expected to see AgentBench folder inside the docker image, but I see none.. All I can see is `data_dev` and `scores_all_data.pkl` under `/root/work/data`.

**Comment by ustc-mkh** [comment]
> @ustc-mkh I'm experiencing similar issue. In fact, I expected to see AgentBench folder inside the docker image, but I see none.. All I can see is `data_dev` and `scores_all_data.pkl` under `/root/work/data`. Did you experience this too?

Yes. I think that docker image is not created by this project, so it's reasonable.

**Comment by Longin-Yu** [comment]
Thanks for your feedback! We upload these files now.
