### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by StupiddCupid** [THUDM/AgentBench#124]
Hi there, I'd like to add Llama2 as an agent to the config file. However, I got a "Connection error" when trying to check if the agent is configured correctly.

<img width="974" alt="Screenshot 2024-03-05 at 8 04 09 PM" src="https://github.com/THUDM/AgentBench/assets/110521637/e993833a-387c-401c-aa57-62e5939d403b">

The fs_agent.yaml as below:

<img width="503" alt="Screenshot 2024-03-05 at 8 04 31 PM" src="https://github.com/THUDM/AgentBench/assets/110521637/369d2306-fe68-4976-966d-79e0ec423437">

I wonder if there is any idea on solving this. Thank you.

**Comment by Longin-Yu** [comment]
Have you deployed a server via FastChat before you start this client?

**Comment by EYH0602** [comment]
to run a FastChat server, the following steps would help

```sh
pip install fastchat
python -m fastchat.serve.controller --host 0.0.0.0
```

in a different terminal (with vicuna-7b as an example):

```sh
python -m fastchat.serve.model_worker --model-path lmsys/vicuna-7b-v1.5 --host 0.0.0.0
```

NOTE: to download the model

```sh
mkdir lmsys & cd lmsys
git clone https://huggingface.co/lmsys/vicuna-7b-v1.5
```

Then you can run a FastChat client

```
> python -m src.client.agent_test --config configs/agents/fs_agent.yaml --agent vicuna-7b 
512
================= USER  ===================
>>> hi
================ AGENT ====================
Hello! How can I help you today? Is there something you would like to talk about or ask me a question? I'm here to assist you with any information or advice you may need.
================= USER  ===================
>>>
```

**Comment by StupiddCupid** [comment]
Solved. Thank you!
