### ISSUE TITLE
OS env

### ISSUE THREAD

**Issue by Lucky-Lance** [THUDM/AgentBench#13]
For the OS environment, where is the file "std.yaml" in the command "python src/tasks/os_interaction/images.py build -c configs/tasks/os_interaction/std.yaml -r ."

**Comment by smittal10** [comment]
Encountering the same error when trying to run the OS task.

**Comment by Longin-Yu** [comment]
Thanks for your interest and sorry for encountering the error. `python src/tasks/os_interaction/images.py build -c configs/tasks/os_interaction/dev.yaml -r .` helps. Now we have updated the image-building code in tutorial.
