### ISSUE TITLE
DB environment error

### ISSUE THREAD

**Issue by Lucky-Lance** [THUDM/AgentBench#14]
After setting the DB environment, I eval and find the following error:

$ python eval.py - -task configs/tasks/dbbench/dev. yam -agent configs/agents/do nothing. yaml

[Warning] FastChat agent not available 
{'module': src. tasks .DBBench', 'parameters': {'name': 'DBBench-dev', 'data file': 'data/dbbench/dev. json', 'max round': 15}}
{ 'module': 'src.agents. DoNothingAgent' parameters: { name: "Do-Nothing-Agent, 'sleep': 0.0177}}
[Evaluation] Loading Agent
[Evaluation] Successfully loaded Agent
[Evaluation] Loadina Task
[Warning] ALFWorld task not available
[Warning] DBBench task not available
[Warning] WebShop task not available
[Warninal LateralThinkinaPuzzle 1 task not available
[Warninal LateralThinkinaPuzzle zh task not available
[Warnina' Mind?Web task not available
Traceback (most recent call last):
File "/home/xdlu/AgentBench/eval.py", line 99, in «module> main ()
File "/home/xdlu/AgentBench/eval.py", line 81, in main
task = assionment tack_ create()
File " /home/xdlu/AgentBench/create assignment .py", , line 43, in create 
return getattr (mod, self .module.split (" .") [-11) (**self .parameters)
AttributeError: module 'src. tasks' has no attribute 'DBBench'

**Comment by zhc7** [comment]
It seems that something failed when loading DBBench environment. Have you installed all the requirements? Including src/tasks/dbbench/requirements.txt. If the issue persists, try removing the `try except` block around dbbench in src/tasks/__init__.py and check out the error message.

**Comment by Longin-Yu** [comment]
Sorry for encountering the error. I've found that `docker_image` field is missing in configuration files. Now fixed. Have a try again?

**Comment by Defiler24** [comment]
I still encountered the same problem. Is there any solution?

**Comment by zhc7** [comment]
have you tried removing the `try except` block?

**Comment by Defiler24** [comment]
> 
I solved the previous problem by installing multiprocess, but encountered a new issue:

Traceback (most recent call last):
  File "anaconda3/envs/agent/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "anaconda3/envs/agent/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File “/AgentBench/src/tasks/dbbench/__init__.py", line 71, in process
    init = build_sql(entry, container.conn)
  File "AgentBench/src/tasks/dbbench/__init__.py", line 35, in build_sql
    [f"`{escape(column['name'], conn)}` TEXT" for column in entry["table"]["table_info"]["columns"]])
  File "AgentBench/src/tasks/dbbench/__init__.py", line 35, in <listcomp>
    [f"`{escape(column['name'], conn)}` TEXT" for column in entry["table"]["table_info"]["columns"]])
  File "AgentBench/src/tasks/dbbench/__init__.py", line 58, in escape
    return conn._cmysql.escape_string(string).decode("utf-8")
  File "anaconda3/envs/agent/lib/python3.8/site-packages/mysql/connector/pooling.py", line 364, in __getattr__
    return getattr(self._cnx, attr)
  File "anaconda3/envs/agent/lib/python3.8/site-packages/multiprocess/process.py", line 315, in _bootstrap
    self.run()
  File "anaconda3/envs/agent/lib/python3.8/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "AgentBench/src/tasks/dbbench/__init__.py", line 71, in process
    init = build_sql(entry, container.conn)
  File "AgentBench/src/tasks/dbbench/__init__.py", line 35, in build_sql
    [f"`{escape(column['name'], conn)}` TEXT" for column in entry["table"]["table_info"]["columns"]])
  File "AgentBench/src/tasks/dbbench/__init__.py", line 35, in <listcomp>
    [f"`{escape(column['name'], conn)}` TEXT" for column in entry["table"]["table_info"]["columns"]])
AttributeError: 'MySQLConnection' object has no attribute '_cmysql'

**Comment by Defiler24** [comment]
> Sorry about the first problem. We've fixed that in the latest commit. Can you share your mysql-connector version?

mysql-connector-python  8.0.33

**Comment by zhc7** [comment]
The problem here appears to be that for some reason you are not using lowlevel C-API. You can try replacing `conn._cmysql.escape_string` with `conn.converter.escape` at `src/tasks/dbbench/__init__.py:58`. See [https://stackoverflow.com/a/32124096/16268001](url). We will try to write a better implementation here to avoid this problem. Thank you for your feedback. @Defiler24

**Comment by Defiler24** [comment]
> The problem here appears to be that for some reason you are not using lowlevel C-API. You can try replacing `conn._cmysql.escape_string` with `conn.converter.escape` at `src/tasks/dbbench/__init__.py:58`. See [https://stackoverflow.com/a/32124096/16268001](url). We will try to write a better implementation here to avoid this problem. Thank you for your feedback. @Defiler24

I replaced 
return conn._cmysql.escape_string(string).decode("utf-8")
with 
return conn.converter.escape(string),
and successfully resolved the issue. Thank you for your assistance.
@zhc7

**Comment by zhc7** [comment]
You're welcome. Thanks for the feedback!
