### ISSUE TITLE
[Feature] Add a LICENSE to the project

### ISSUE THREAD

**Issue by cjoverbay** [THUDM/AgentBench#141]
**Is your feature request related to a problem? Please describe.**
Without a license it makes it difficult to use the code.

**Describe the solution you'd like**
Choose an open source license and add it to the project. (MIT, Apache2 etc.)

**Comment by jim-schwoebel** [comment]
+1

**Comment by zhc7** [comment]
Thanks for your suggestion! We have a license now.
