### ISSUE TITLE
Discussion:  Next Version Requirements and Improvements

### ISSUE THREAD

**Issue by Longin-Yu** [THUDM/AgentBench#15]
Thank you for your interest in our project. We are planning to refactor this framework in the next few weeks. We really hope that you can provide some suggestions.

We think it is imperative to **refactor the task section**. It may be more elegant if task is **seperated into client and server** like what we have done on agents, i.e., **deployed as http service**. Spawning **multiple processes** in a single evaluation process makes it less easy to track down bugs.

**Comment by vaxilicaihouxian** [comment]
May be add a category `code generate` to solve problem with a code interpreter?
Give some functions to llm with prompt and let it generate code block to solve problem.

**Comment by olivarb** [comment]
Is there an expected release date for the refactor? Was it force pushed?

**Comment by zhc7** [comment]
We just released AgentBench v0.2 yesterday.

**Comment by Xiao9905** [comment]
@olivarb Thanks for your interest in AgentBench. Do you have any further comment? Please feel free to reopen the issue if you find it necessary.
