### ISSUE TITLE
[Bug/Assistance] kg的这个任务，http://164.107.116.56:3093/sparql这个服务器地址，似乎宕机了，执行python src/server/tasks/knowledgegraph/utils/sparql_executer.py会超时

### ISSUE THREAD

**Issue by minleminzui** [THUDM/AgentBench#153]
**Describe the bug**

**To Reproduce**

**Screenshots or Terminal Copy&Paste**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Python: [e.g. 3.9]

**Additional context**

**Comment by zhc7** [comment]
确实，目前这个服务器正在维护，本地部署可以参考https://github.com/dki-lab/Freebase-Setup

**Comment by minleminzui** [comment]
> 确实，目前这个服务器正在维护，本地部署可以参考https://github.com/dki-lab/Freebase-Setup

好的，非常感谢

**Comment by minleminzui** [comment]
请问你们这个服务大概什么时候能够维护好呢
