### ISSUE TITLE
[Bug/Assistance] 'NoneType' object has no attribute 'retrieve'

### ISSUE THREAD

**Issue by YerongLi** [THUDM/AgentBench#176]
`'NoneType' object has no attribute 'retrieve' `

I received this message on testing. Does anyone know how to fix this?
![Screenshot from 2024-12-06 09-15-00](https://github.com/user-attachments/assets/534c6402-e860-4b75-91b3-af5167808e2e)

**Comment by echo777-my** [comment]
Hi, how did you fix it?
