### ISSUE TITLE
How to interpret the assessment results

### ISSUE THREAD

**Issue by foamliu** [THUDM/AgentBench#18]
For example, if you use llama 2 70B to run the AFLWorld evaluation, the results.json generated in the outputs directory after the evaluation is as follows:

![image](https://github.com/THUDM/AgentBench/assets/14009435/59ff1940-a1b6-49c5-9888-8e6d4b49d974)

How to interpret this result. Is there a total of 20 test samples? In Table 3 of the Leaderboard on the homepage, GPT-4 scored 78.0 in ALFWorld. If there are only 20 samples, this score cannot be obtained, right?

**Comment by zhc7** [comment]
You can refer to README.md. As shown in "Dataset summary" section, you are using dev set, but results in the paper were tested with test set.
