### ISSUE TITLE
CardGame task always runing

### ISSUE THREAD

**Issue by cicyby** [THUDM/AgentBench#19]
![image](https://github.com/THUDM/AgentBench/assets/30401160/16fa8d16-bdd5-43b8-87fa-f112618f7f16)
Verification process stuck here ...

Is there a problem with docker communication？

**Comment by foamliu** [comment]
I have encountered the same problem here, do we need to configure the environment?

Suggestions: 
1. Introduces how to configure the environment in doc; 
2. Raise timeout & exit when the environment is unavailable.

**Comment by harshraj172** [comment]
I had the same error. Tried with `workers=16`, which worked.

**Comment by cyente** [comment]
I had the same error. While workers=16, does not work. It seems that  it is hang on myAI.run(). Could someobe give a detail example of how the run cardGame?

**Comment by sjqgogogo** [comment]
I had the same error and I solved this by running on docker. You can use command in ./scripts/eval_utils.sh or create your own assignment by using create_assignmnet.py(https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md) to run the evaluation on docker.
