### ISSUE TITLE
Request to update scores of claude models

### ISSUE THREAD

**Issue by wooparadog** [THUDM/AgentBench#21]
Hi, 

Anthropic has released their new `claude-2` and `claude-instant-1.2`. It'll be nice to have their scores updated.

ref:

1. https://www.anthropic.com/index/releasing-claude-instant-1-2
2. https://docs.anthropic.com/claude/reference/selecting-a-model
3. https://www.anthropic.com/index/claude-2

**Comment by nullbio** [comment]
Code-Llama would also be interesting to see.

**Comment by alramalho** [comment]
Any news here?

**Comment by zhc7** [comment]
Hi, we've updated the result.

**Comment by alramalho** [comment]
Where?
I dont see it here nor in the README
https://llmbench.ai/agent/data

**Comment by zhc7** [comment]
Please make sure you are on branch main. You can see the result of claude-2 and codellama here https://github.com/THUDM/AgentBench#leaderboard. We'll upload the new data to our website shortly.
