### ISSUE TITLE
OS任务镜像构建失败

### ISSUE THREAD

**Issue by MrPig** [THUDM/AgentBench#23]
按照tutorial 描述，执行 `python src/tasks/os_interaction/images.py build -c configs/tasks/os_interaction/dev.yaml -r .` 会报错。报错信息：
`docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.40/images/local-os/packages/json: Not Found ("no such image: local-os/packages: No such image: local-os/packages:latest")`

看了下代码 src/tasks/os_interaction/images.py ，发现三行一样的，是不是写错了
![image](https://github.com/THUDM/AgentBench/assets/3120446/851f5785-fce6-49f0-ab87-c0928fc5f52b)

**Comment by YuechengLiu** [comment]
你好，我也遇到了这个问题，请问怎么解决的呢？
