### ISSUE TITLE
Mind2web issue

### ISSUE THREAD

**Issue by Anticope12** [THUDM/AgentBench#27]
Hello team, 
All the tasks working except Mind2web. 

 python eval.py \
    --task configs/tasks/mind2web/dev.yaml \
    --agent configs/agents/do_nothing.yaml \

after running the following I'm getting the following error:

    raise FileNotFoundError(f"No (supported) data files or dataset script found{path}")
FileNotFoundError: No (supported) data files or dataset script found in ..

**Comment by zhc7** [comment]
Hi, maybe you could try running this task in docker with our prebuilt image.

**Comment by Longin-Yu** [comment]
We have released a new version. Welcome to have a try! 🤗

**Comment by Xiao9905** [comment]
@Anticope12 Hi, thanks for your interest in AgentBench. Do you still have some problem with the Mind2Web evaluation? Please feel free to reopen the issue if you need help.
