### ISSUE TITLE
The evaluation of knowledge graph always get zero

### ISSUE THREAD

**Issue by cyente** [THUDM/AgentBench#29]
I have totally follow the [tutorial](https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md). and installed Freebase-Setup. 

When running KG tasks, the result always get zero, even if i use gpt4. 

There is not any error information in log. Is there any suggestion on it?

**Comment by YuechengLiu** [comment]
> I have totally follow the [tutorial](https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md). and installed Freebase-Setup.
> 
> When running KG tasks, the result always get zero, even if i use gpt4.
> 
> There is not any error information in log. Is there any suggestion on it?

I meet the same problem, have you figured it out?

**Comment by zhc7** [comment]
Would you provide more detailed information? Such as files in output directory, including `jsonl`s and `yaml`s

**Comment by YuechengLiu** [comment]
> Would you provide more detailed information? Such as files in output directory, including `jsonl`s and `yaml`s

The evaluation runs successfully.

**Comment by matinaghaei** [comment]
I'm having the same issue. It looks like that the language model is calling the right function, but the task insists that the model has made a mistake. For example:

`{"role": "user", "content": "A new question: Which suprbowls were won by an NFL team that played in the New York Metropolitan area?\nEntities: [suprbowls, New York metropolitan area]"}, {"role": "agent", "content": "Thought: I need to first find NFL teams that played in the New York Metropolitan area. To achieve this, I will query the KB to find relations connected to the entity 'New York metropolitan area'.\nAction: get_relations(New York metropolitan area)"}, {"role": "user", "content": "get_relations(New York metropolitan area) cannot be executed. You may make a mistake and need to fix it."}`
