### ISSUE TITLE
python: can't open file 'evaluate.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Elissa0723** [THUDM/AgentBench#30]
python evaluate.py \
    --task configs/tasks/knowledgegraph/dev.yaml \
    --agent configs/agents/local/do_nothing_agent.yaml \
    --workers 30
   
It seems should be updated like code below?

python eval.py \
    --task configs/tasks/knowledgegraph/dev.yaml \
    --agent configs/agents/do_nothing.yaml \
    --workers 30

**Comment by zhc7** [comment]
Yes, thank you! We've fixed that.
