### ISSUE TITLE
Traces of different evaluations

### ISSUE THREAD

**Issue by Andrewzh112** [THUDM/AgentBench#36]
Is it possible to provide the trajectory traces of different evaulations?

**Comment by zhc7** [comment]
Are you looking for runs.jsonl in the result directory?

**Comment by Andrewzh112** [comment]
> Are you looking for runs.jsonl in the result directory?

Yes, where is it located? I couldn't find it. Thanks

**Comment by zhc7** [comment]
You can run a evaluation following docs/tutorial.md, and then you'll see the output dir.

**Comment by Xiao9905** [comment]
@Andrewzh112 Hi, thanks for your interest in AgentBench. Has your problem been solved successfully? Feel free to reopen the issue if you need more help.
