### ISSUE TITLE
docker preparation: webshop

### ISSUE THREAD

**Issue by Hua-rookie** [THUDM/AgentBench#37]
When I prepare dockers using `bash scripts/build_docker.sh`, I meet the "ERROR: failed to solve: failed to register layer: write /root/miniconda3/lib/libicudata.so.58.2: no space left on device" in the preparation for webshop.

**Comment by Hua-rookie** [comment]
But there is quite enough space in my disks, so I wonder why this error happen and how can I solve it?

**Comment by zhc7** [comment]
How much space do you have left? This docker image do require a lot of disk space. The image itself is about 27G large.

**Comment by Hua-rookie** [comment]
> How much space do you have left? This docker image do require a lot of disk space. The image itself is about 27G large.

more than 100G

**Comment by Hua-rookie** [comment]
Oh god, I forget to change the VM in my docker desktop which is not enough for installation of webshop docker.

**Comment by Hua-rookie** [comment]
Oh god, I forget to change the VM in my docker desktop which is not enough for installation of webshop docker. Now it works.
