### ISSUE TITLE
Access to Test  Sets

### ISSUE THREAD

**Issue by guosyjlu** [THUDM/AgentBench#39]
Hi, thanks for your wonderful benchmark project!
I wonder know how to evaluate on test set to derive the leaderboard score? Do we only allow evaluation on the dev set in the current version? If yes, is there any plan to make us have access to evaluate on test set?
Thanks for your possible help!

**Comment by zhc7** [comment]
We are currently planning to set up a test server in the future which allows submission. But temporarily we are not planning to release the full set.

**Comment by olivarb** [comment]
So currently, the script does not allow us to profile our own LLMs for comparison to the published results?

**Comment by zhc7** [comment]
Thanks for your interest. Actually we've released all datasets in AgentBench v0.2. You may take a look at our updated README for more information.

**Comment by 1049451037** [comment]
So... How to get test set evaluation score without docker? I don't have a machine that can run docker...
