### ISSUE TITLE
我在按照turorial时遇到的问题

### ISSUE THREAD

**Issue by ChangFeng2015** [THUDM/AgentBench#40]
![image](https://github.com/THUDM/AgentBench/assets/11408764/5126561c-d40a-46f8-b819-ebbbf6abb1c4)
![image](https://github.com/THUDM/AgentBench/assets/11408764/9aab92bd-534b-4844-aeee-e13e5e574497)
服务器环境已经安装相应的docker环境，但在执行 sh .assignment/**.sh过程中出现图1中的现象，请问一下这是怎么回事，运行这个服务器要架设vpn么？

**Comment by zhc7** [comment]
从你的docker ps来看，你只是创建了container但并没有运行呀

**Comment by zhc7** [comment]
上次漏看了一个图，你第一幅图里第二个红框里面是一个网络连接错误，你确定你现在的网络环境可以正常访问api.openai.com吗？至于你框出的warning，是因为你没有下载对应的docker image或者没有配置相应的系统环境，因此任务无法加载。

**Comment by dong-river** [comment]
> 上次漏看了一个图，你第一幅图里第二个红框里面是一个网络连接错误，你确定你现在的网络环境可以正常访问api.openai.com吗？至于你框出的warning，是因为你没有下载对应的docker image或者没有配置相应的系统环境，因此任务无法加载。

[在这里](https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md#step-3-prepare-the-requirements-for-each-task) 你们好像只给了三个task怎么create docker，其他的怎么样装啊

**Comment by Longin-Yu** [comment]
我们更新了 v0.2，欢迎尝试~ 如果有任何问题，欢迎提出新的 issue！
