### ISSUE TITLE
DBBench failed

### ISSUE THREAD

**Issue by nlpcat** [THUDM/AgentBench#45]
when I followed the tutorial, I got an error for DBBench like this 
```
File "AgentBench/src/tasks/dbbench/__init__.py", line 136, in __init__
    p.start()
...
  File "/miniconda/base/envs/AgentBench/lib/python3.11/site-packages/multiprocess/util.py", line 452, in spawnv_passfds
    return _posixsubprocess.fork_exec(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: fork_exec() takes exactly 23 arguments (21 given)
```

**Comment by Longin-Yu** [comment]
what's your python version?

**Comment by zhc7** [comment]
Would you like to try it again with v0.2? The problem should no longer exist.

**Comment by Xiao9905** [comment]
@nlpcat Hi, thanks for your interest in AgentBench. How is it going with your testing on DBBench? Please feel free to reopen this issue for our further assistance.
