### ISSUE TITLE
webshop stuck at 78/80 

### ISSUE THREAD

**Issue by harshraj172** [THUDM/AgentBench#49]
Warning: 4 messages are omitted.
Warning: 4 messages are omitted.
 98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 78/80 [26:04<00:16,  8.11s/it]

Webshop evaluation is stuck at 78/80 iteration, its been 2hrs and it is not proceeding.
Any help is deeply appreciated.
-Thanks

**Comment by Longin-Yu** [comment]
We fix this in v0.2 (add timeout + resume evaluation), welcome to have a try!

**Comment by Xiao9905** [comment]
@harshraj172 Hi, how is it going with your testing on webshop? Please feel free to reopen the issue if you need our help.
