### ISSUE TITLE
Running in Colab

### ISSUE THREAD

**Issue by olivarb** [THUDM/AgentBench#51]
Is there any support to run this in Colab?

**Comment by Longin-Yu** [comment]
That may be difficult because this project is not a single-process program. But if you find a way to deploy the task servers, the evaluation process can be executed in Colab.

**Comment by olivarb** [comment]
Would there be any support for this in the future? It would make it easier to profile models

**Comment by olivarb** [comment]
@zhc7 Would it be possible to run without Docker? This would likely make it viable to run in Colab

**Comment by zhc7** [comment]
Hi, running different tasks in the same environment can be really complicated. Requirements of different tasks may conflict with each other. If you insist, you may remove the `docker` field in configs and try to setup the environment manually. I haven't tried it myself, so I don't know if it's feasible.

**Comment by olivarb** [comment]
@zhc7 Will there be any official support for this use case? It is easy to spin up multiple colab sessions

**Comment by zhc7** [comment]
Thanks for your advice. But this is a rather complicated problem and we haven't planned to support this recently. If you managed to solve this problem, we're always open to contributions.

**Comment by dsubunow** [comment]
Hi, is it possible to get a requirements.txt file for individual tasks? Or a dockerfile (as opposed to a docker image)?

**Comment by YerongLi** [comment]
Did you figure out how to run without docker?
