### ISSUE TITLE
There are some error questions in data/knowledgegraph/std.json

### ISSUE THREAD

**Issue by kev123456** [THUDM/AgentBench#61]
There are some error questions in "data/knowledgegraph/std.json" file:
Such as:
     "question": "When was the last superbowl to inlucde the team that had Rise as thier mascot?",
     "qid": "WebQTest-595_5dd0eeca79ae03b7711252c032849eb2_cwq",

Was it intentionally set up ？

**Comment by Longin-Yu** [comment]
This problem is adapted from ComplexWebQuestions. In the original construction process of these datasets, there were instances where questions were deliberately created to pursue multi-hop relationships, resulting in some unnatural queries.

**Comment by Xiao9905** [comment]
@kev123456 Hi, thanks for your interest in AgentBench? Do you have further questions? Please feel free to reopen the issue and ask if you have.
