### ISSUE TITLE
[Feature] 是否有方法可以使用多个chatgpt的api_key，这样可以减少访问限制的情况发生

### ISSUE THREAD

**Issue by nov3630** [THUDM/AgentBench#64]
是否有方法可以使用多个chatgpt的api_key，这样可以减少访问限制的情况发生

**Comment by zhc7** [comment]
这个我们将来会考虑优化一下这方面的设计。目前有几个解决办法：
1. 自行布置一个openai请求的转发服务器，里面做一个key pool
2. 修改src/client/agents/http_agent.py里面的实现 支持从config中读取一个或多个key并合理分配请求

如果实现了2，我们欢迎pr！

**Comment by ssunoo** [comment]
#191 Implement 2. by simply invoking each api key in rotation.
