### ISSUE TITLE
Mind2Web webshop data is not found in this repo?

### ISSUE THREAD

**Issue by cyente** [THUDM/AgentBench#7]
如题

**Comment by scottsuk0306** [comment]
I'm also curious about this. How can I replicate the Mind2Web results?

**Comment by Longin-Yu** [comment]
We recommend pulling docker images for these tasks (except for OS, DB, KG for which we do not provide docker images)

**Comment by Longin-Yu** [comment]
You can refer to https://github.com/THUDM/AgentBench/blob/main/docs/tutorial.md#step-2-prepare-docker-environment
