### ISSUE TITLE
[Assistance] How to change the prompt in the task

### ISSUE THREAD

**Issue by Z-ZHHH** [THUDM/AgentBench#76]
**Assistance**
 Thanks for the benchmark.
I want to change the prompts in the agent task. For example, replace the original with the hand-craft prompts. In AgentBench1.0, I can do this by modifying the file (AgentBench/src/server/tasks/webshop/__init__.py). However, this method dont work in AgentBench 2.0, could anyone help with that?

**Comment by zhc7** [comment]
Hi, @Z-ZHHH . Theoractically, modifying `src/server/tasks/webshop/init.py` should work. Can you share why you think it didn't work? Did you restart the task worker after modifying the file?

**Comment by Z-ZHHH** [comment]
I forget to restart the task worker after modifying, this is an additional step compared to AgentBench 1.0. Thanks a lot for the help!
