### ISSUE TITLE
运行AgentBench报错

### ISSUE THREAD

**Issue by QingChengLineOne** [THUDM/AgentBench#78]
![image](https://github.com/THUDM/AgentBench/assets/111961874/ef345ee4-b3b8-4df3-9d5c-c00e5a90fbae)

**Comment by zhc7** [comment]
Hi, @QingChengLineOne 这个问题依然存在吗？可以展示一下你的配置文件吗？

**Comment by pfx546746447** [comment]
> Hi, @QingChengLineOne 这个问题依然存在吗？可以展示一下你的配置文件吗？

我也有同样的问题，只是我是403，配置文件是看这个么
![WechatIMG13](https://github.com/THUDM/AgentBench/assets/15622470/be47fc42-3aef-4244-9a17-c8a11fd29c36)
