### ISSUE TITLE
Error with Command “python -m src.start_task -a”

### ISSUE THREAD

**Issue by ericzdzhang** [THUDM/AgentBench#84]
![issue](https://github.com/THUDM/AgentBench/assets/152348885/1f93eaad-752c-44ce-8009-a01c0c6800f5)

I have been testing on a Mac system and have confirmed that there are no issues with invoking ChatGPT. However, I encountered an error while running "python -m src.start_task -a". Could you please help me investigate the possible cause of this problem?

**Comment by zhc7** [comment]
Hi @ericzdzhang , have you installed docker?

**Comment by ericzdzhang** [comment]
Yes，I Install docker on the Mac OS. It seems due to the communication error in docker.



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/12/2023 15:39 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [THUDM/AgentBench] Error with Command “python -m src.start_task -a” (Issue #84) |

Hi @ericzdzhang , have you installed docker?

**Comment by ZiyueWang25** [comment]
I have met similar issue in mac. The solution is in https://stackoverflow.com/questions/69955686/why-cant-i-run-the-project-on-port-5000. After I follow it, the issue is gone.

**Comment by zhc7** [comment]
@ZiyueWang25 Thanks!

**Comment by petrgazarov** [comment]
For anyone still seeing this error after making port 5000 available: ensure file `/var/run/docker.sock` exists because this is what the code uses to connect to the Docker Daemon. My file was in a different location, so I had to create a symlink:

```
sudo ln -s $HOME/.docker/run/docker.sock /var/run/docker.sock
```
