### ISSUE TITLE
[Assistance] Connection Error

### ISSUE THREAD

**Issue by wz1211** [THUDM/AgentBench#86]
**Describe the bug**
api类模型可以正常运行
于是尝试使用OSS类模型（如vicuna），但对话显示Connection Error，不知道是不是fastchat有什么需要配置

**To Reproduce**
运行 `python -m src.client.agent_test --config configs/agents/fs_agents.yaml --agent vicuna-7b`
输入User信息后报错 `Connection Error`

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22.04]
在服务器上运行

**Comment by Taishi-N324** [comment]
@wz1211 
Were you able to resolve this issue?
