### ISSUE TITLE
我想看一下agent和server的交互函数，可以指导一下嘛

### ISSUE THREAD

**Issue by hushuang909** [THUDM/AgentBench#92]
**Describe the bug**

**To Reproduce**

**Screenshots or Terminal Copy&Paste**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Python: [e.g. 3.9]

**Additional context**

**Comment by zhc7** [comment]
Hi, @hushuang909 ，如果指的是task server的话，相应的代码在`src/client/task.py`里。如果指的是agent server的话，相应的代码在`src/client/agents`里。

**Comment by zhc7** [comment]
If you have any further questions, you are welcome to reopen the issue!
