### ISSUE TITLE
可否不用docker配置环境

### ISSUE THREAD

**Issue by smartliuhw** [THUDM/AgentBench#93]
目前我的开发机无法连接外网，也不能配置docker，请问一下有没有不用docker配置环境的方法，感谢🙏！

**Comment by zhc7** [comment]
Hi, @smartliuhw 。可以是可以，但过程会非常繁琐。可以逐个遍历`src/server/tasks`下面的每一个任务，按照相应的要求配置好环境。注意，环境之间很可能是有冲突的，我们不保证存在一个环境可以同时运行所有task。同时，我们也并没有设计手动配置所有环境，所以可能并没有足够的文档支持相应的步骤。如果环境配置完成了，可以修改`configs/tasks`下面相应的配置文件，移除`docker`字段即可。

**Comment by smartliuhw** [comment]
> Hi, @smartliuhw 。可以是可以，但过程会非常繁琐。可以逐个遍历`src/server/tasks`下面的每一个任务，按照相应的要求配置好环境。注意，环境之间很可能是有冲突的，我们不保证存在一个环境可以同时运行所有task。同时，我们也并没有设计手动配置所有环境，所以可能并没有足够的文档支持相应的步骤。如果环境配置完成了，可以修改`configs/tasks`下面相应的配置文件，移除`docker`字段即可。

感谢回复！前两天尝试了一下没跑通，先尽量找了台能联网的机器用着了🤦
